name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Start Linker Fixer Daemon
        run: |
          (
            echo "Watcher started. Waiting for toolchain..."
            while true; do
              if [ -f "/home/runner/clang/bin/ld" ]; then
                echo "Conflicting linker found! Deleting..."
                rm -f /home/runner/clang/bin/ld
                echo "Conflicting linker removed successfully."
                break
              fi
              sleep 1
            done
          ) &

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/pjjaxvyn2020/moonbeam_gale_kernel
          kernel-branch: mb-gamma
          config: gale_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          other-clang-url: https://github.com/kdrag0n/proton-clang
          other-clang-branch: master
          ksu: false
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: false
          anykernel3: true

      # ADD THIS NEW STEP HERE:
      - name: Copy DTBO to AnyKernel3
        run: |
          cp kernel/kernel/out/arch/arm64/boot/dts/mediatek/gale.dtbo AnyKernel3/dtbo.img
